DROP TABLE IF EXISTS TBL_HELLO;

CREATE TABLE TBL_HELLO (
    id INT AUTO_INCREMENT PRIMARY KEY,
    leanguage VARCHAR(250) NOT NULL,
    hello VARCHAR(250) NOT NULL,
    world VARCHAR(250) NOT NULL
);
